### ISSUE TITLE
bot no run

### ISSUE THREAD

**Issue by ependd** [akasakaid/pixelversexyzbot#6]
![Screenshot_20240516-065847.png](https://github.com/akasakaid/pixelversexyzbot/assets/137770771/8a47fdd7-917b-45a8-862b-9781804c2c21)

**Comment by ependd** [comment]
I've done according to the instructions but it's still like this

**Comment by ependd** [comment]
I've done according to the instructions but it's still like this

**Comment by akasakaid** [comment]
```
cp .env.example .env
```
